server {
    listen 80;
    server_name lmsmoodletest.xyz;

    root /var/www/html/moodle/public;
    index index.php index.html;

    # Info bahwa koneksi dari Cloudflare adalah HTTPS
    fastcgi_param HTTPS on;
    fastcgi_param HTTP_X_FORWARDED_PROTO https;

    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 131.0.72.0/22;
    real_ip_header CF-Connecting-IP;

    client_max_body_size 50M;
# Blokir akses langsung ke halaman login
location = /login/index.php {
     if ($http_cookie !~* "verified=1") {
        return 302 /verifikasi.php;
    }
    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
}
    # Blokir akses ke file dan folder sensitif
    location ~* \.(env|git|phpinfo|wp-admin|wp-login|xmlrpc|bak|old|sql|tar|gz|zip|rar|7z)$ {
        return 404;
    }
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* (nginx-status|server-status|config\.php~) {
        return 404;
    }

    # Security Headers
add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), interest-cohort=()" always;
    add_header Cross-Origin-Embedder-Policy "unsafe-none" always;
    add_header Cross-Origin-Opener-Policy "unsafe-none" always;
    add_header Cross-Origin-Resource-Policy "cross-origin" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://h5p.org https://*.h5p.org https://www.recaptcha.net https://www.google.com https://www.gstatic.com https://www.youtube.com https://challenges.cloudflare.com https://static.cloudflareinsights.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://h5p.org https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://h5p.org https://*.h5p.org https://www.recaptcha.net https://www.youtube.com https://www.google-analytics.com https://www.google.com; frame-src 'self' https://h5p.org https://*.h5p.org https://www.recaptcha.net https://www.google.com https://www.youtube.com https://challenges.cloudflare.com; object-src 'none';" always;
#location = / {
 #   return 302 /verify.html;
#}

location / {
    try_files $uri $uri/ /index.php?$query_string;
}
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /moodledata {
        deny all;
        return 404;
    }
}
